"$schema" = "https://starship.rs/config-schema.json"

add_newline = false

format = """
$cmd_duration\
$jobs\
$sudo\
$character
"""

right_format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$python\
$rust\
$golang\
$docker_context\
$package\
$time
"""

# =========================
# CHARACTER
# =========================

[character]
success_symbol = "[❯](bold fg:#EAEAEA)"
error_symbol = "[❯](bold fg:#7F7F7F)"

# =========================
# CMD DURATION
# =========================

[cmd_duration]
min_time = 500
format = "[◄ $duration](fg:#7A7A7A) "

# =========================
# JOBS
# =========================

[jobs]
symbol = "⚙ "
style = "fg:#BDBDBD"
format = "[$symbol$number]($style) "

# =========================
# SUDO
# =========================

[sudo]
disabled = false
symbol = "󰌾 "
style = "fg:#BDBDBD"
format = "[$symbol]($style)"

# =========================
# DIRECTORY
# =========================

[directory]
home_symbol = "~"
truncation_length = 3
truncation_symbol = "../"
style = "fg:#D6D6D6"

format = "[󰉋 $path]($style) "

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Pictures" = ""
"Desktop" = ""
"GitHub" = ""

# =========================
# GIT BRANCH
# =========================

[git_branch]
symbol = " "
style = "fg:#E0E0E0"

format = "[$symbol$branch]($style) "

truncation_length = 20
truncation_symbol = "…"

# =========================
# GIT STATUS
# =========================

[git_status]
style = "fg:#AFAFAF"

format = "[$all_status$ahead_behind]($style)"

ahead = "󰁝 "
behind = "󰁅 "
diverged = "󰹹 "
untracked = "󰞋 "
modified = "󰷈 "
staged = "󰄬 "
renamed = "󰑕 "
deleted = "󰆴 "
stashed = "󰏗 "
conflicted = "󰞇 "

# =========================
# NODE
# =========================

[nodejs]
symbol = "󰎙 "
style = "fg:#D8D8D8"

format = "[$symbol$version]($style) "

version_format = "${raw}"

# =========================
# PYTHON
# =========================

[python]
symbol = "󰌠 "
style = "fg:#D8D8D8"

format = "[$symbol$version]($style) "

version_format = "${raw}"

# =========================
# RUST
# =========================

[rust]
symbol = "󱘗 "
style = "fg:#D8D8D8"

format = "[$symbol$version]($style) "

version_format = "${raw}"

# =========================
# GO
# =========================

[golang]
symbol = " "
style = "fg:#D8D8D8"

format = "[$symbol$version]($style) "

# =========================
# DOCKER
# =========================

[docker_context]
symbol = " "
style = "fg:#D8D8D8"

format = "[$symbol$context]($style) "

only_with_files = true

# =========================
# PACKAGE
# =========================

[package]
symbol = "󰏗 "
style = "fg:#C0C0C0"

format = "[$symbol$version]($style) "

# =========================
# TIME
# =========================

[time]
disabled = false

time_format = "%H:%M"

style = "fg:#7A7A7A"

format = "[$time]($style)"